version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: pagamento-db
    environment:
      - POSTGRES_DB=pagamento
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - 5435:5432
  rabbitmq:
    image: "rabbitmq:3.8.6-management"
    container_name: rabbitmq-masterdev
    ports:
      - 5672:5672
      - 15672:15672


  app:
    depends_on:
      - postgres
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5435/pagamento
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8084:8084"
    networks:
      - my-networks

networks:
  my-networks:
    driver: bridge
